name: Update labels
on:
  project_card:
    types: [created, deleted, moved]
jobs:
  remove_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            echo '${{ toJSON(github.event) }}' >> $GITHUB_STEP_SUMMARY